In [ ]:
#SECTION A : DATA STRUCTURES & CONTROL STRUCTURES 

In [78]:
# 1.LIST OF 5 Integers and perform caluclation 

List1 =[22,20,26,24,28,"s","s","s"]
print(List1)

List1.append(30) 
print(List1)

List1.extend("r")
print(List1)

List1.insert(1,21) 
print(List1)

List1.remove("r")
print(List1)

List1.pop(1) 
print(List1)

print(List1.index(22))  

List1.count("s")



[22, 20, 26, 24, 28, 's', 's', 's']
[22, 20, 26, 24, 28, 's', 's', 's', 30]
[22, 20, 26, 24, 28, 's', 's', 's', 30, 'r']
[22, 21, 20, 26, 24, 28, 's', 's', 's', 30, 'r']
[22, 21, 20, 26, 24, 28, 's', 's', 's', 30]
[22, 20, 26, 24, 28, 's', 's', 's', 30]
0


3

In [84]:
List1=[3, 5,1,0,8,]
List1.sort()
print(List1)
List1.reverse() 
print(List1)

[0, 1, 3, 5, 8]
[8, 5, 3, 1, 0]


In [88]:
# 2 answer
tuple1=("rinky","rithu","chiru")

# Tuple is inmutable thats why it cannot change second name
# Immutable means once a tuple is created, its elements cannot be changed, added, or removed.


In [98]:
# 3 - Answer
set1 = {7,1,2,3,2,4,4,5,5,6,6}
set1
#  Even though you added 2 and 3 multiple timesthe set automatically removes duplicates and keeps just one copy of each.
# Sets are unordered Collections
# sets remove duplicates and it represents in ascending order 

{1, 2, 4, 5, 6, 7}

In [126]:
#4-Answer
D = { "name":"Rithika", "age":21 ,"city":"Hyderabad"}
D
D["age"]=22
D
D["email"]="ri@gmail.com"
D

{'name': 'Rithika', 'age': 22, 'city': 'Hyderabad', 'email': 'ri@gmail.com'}

In [132]:
# 5 - Answer
Age = int(input("enter age of person"))
if Age>=18:
    print("PERSON FOR ELGIBLE VOTE ")
else: 
    print("NOT ELGIBLE FOR VOTE")

enter age of person 45


PERSON FOR ELGIBLE VOTE 


In [9]:
# 6- Answer Marks grading 
marks = int(input("enter total marks"))
if marks >= 90:
    print("GRADE-A")
elif marks >= 75:
    print("GRADE-B")
elif marks >= 50:
    print("GRADE-C")
else:
    print("FAIL")

            

enter total marks 69


GRADE-C


In [32]:
# 7 POSITIVE OR NEGATIVE NUMBER 
number = int(input("enter number"))
if number > 0:
    if number % 2 ==0:
       print("POSITIVE AND EVEN NUMBER")
    else:
       print("Positive but Odd ")
elif number == 0:
    print("NUMBER IS ZERO OR NEGATIVE") 


enter number 56


POSITIVE AND EVEN NUMBER


In [ ]:
# SECTION 2 NUMPY

In [66]:
#8.	Create:
import numpy as np
#- A scalar using np.array(5)
scalar = np.array(5)
print(scalar) 
#- A 1D array with values 1 to 5
array_1D = np.array([1,2,3,4,5])
print(array_1D)
# - A 2D array (2x3) with values from 10 to 60 in steps of 10
array_2D = np.array([[10,20,30] , [40,50,60]])
print(array_2D)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [68]:
#9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
np.random.randint(0,100,size=(4,4)) 

array([[ 3,  5, 87, 16],
       [66, 43, 89, 52],
       [80, 20, 53, 36],
       [71,  9, 23, 47]])

In [86]:
#10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'
import pandas as pd 
array_2 =np.random.randint(0,20,size=(3,3)) 
df=pd.DataFrame(array_2)
df.columns=["A","B","C"]
print(df)

    A   B   C
0  11  16   6
1   3   9  15
2   9  18   7


In [150]:
#Section C: Exploring Pandas
#    11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
#- Select 'Name' and 'City' columns
#- Drop 'City' column
#- Fill any missing values in 'Salary' column with the mean
#- Remove any duplicate rows
data = {
    'Name': ['jaya', 'sai', 'rithu', 'virat', 'shilpa',
             'vinay', 'kumar', 'shree', 'chandana', 'Julie'],
    'Age': [25, 30, 35, 28, 40,
            32, 27, 29, 31, 26],
    'City': ['Hyd', 'Chennai', 'Delhi', 'Pune', 'Mysore',
             'Kolkata', 'Benguloor', 'Maharastra', 'Vizag', 'Hyd'],
    'Salary': [50000,np.nan, 75000, 52000, 82000,
               58000, 49000, 53000, np.nan, 56000]
}
df = pd.DataFrame(data)

print(df)


       Name  Age        City   Salary
0      jaya   25         Hyd  50000.0
1       sai   30     Chennai      NaN
2     rithu   35       Delhi  75000.0
3     virat   28        Pune  52000.0
4    shilpa   40      Mysore  82000.0
5     vinay   32     Kolkata  58000.0
6     kumar   27   Benguloor  49000.0
7     shree   29  Maharastra  53000.0
8  chandana   31       Vizag      NaN
9     Julie   26         Hyd  56000.0


In [146]:
##- Use .info()
df.info(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes


In [112]:
#- Use describe()
df.describe()

Age       Salary
count  10.000000     10.00000
mean   30.300000  59600.00000
std     4.522782  10864.82602
min    25.000000  49000.00000
25%    27.250000  52250.00000
50%    29.500000  57000.00000
75%    31.750000  60750.00000
max    40.000000  82000.00000

In [193]:
#- Select 'Name' and 'City' columns
df[['Name', 'City']]


Name        City
0      jaya         Hyd
1       sai     Chennai
2     rithu       Delhi
3     virat        Pune
4    shilpa      Mysore
5     vinay     Kolkata
6     kumar   Benguloor
7     shree  Maharastra
8  chandana       Vizag
9     Julie         Hyd

In [140]:
#Drop 'City' column"])
df.drop("City" ,axis=1)


Name  Age  Salary
0      jaya   25   50000
1       sai   30   60000
2     rithu   35   75000
3     virat   28   52000
4    shilpa   40   82000
5     vinay   32   58000
6     kumar   27   49000
7     shree   29   53000
8  chandana   31   61000
9     Julie   26   56000

In [166]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    2
dtype: int64

In [168]:
data=df["Salary"].mean()

In [174]:
df['Salary'].fillna(value=data,inplace=True)

C:\Users\RITHIKA\AppData\Local\Temp\ipykernel_12376\373926278.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(value=data,inplace=True)


In [176]:
df.isnull().sum()

Name      0
Age       0
City      0
Salary    0
dtype: int64

In [189]:
df.drop_duplicates()
print(df)




       Name  Age        City   Salary
0      jaya   25         Hyd  50000.0
1       sai   30     Chennai  59375.0
2     rithu   35       Delhi  75000.0
3     virat   28        Pune  52000.0
4    shilpa   40      Mysore  82000.0
5     vinay   32     Kolkata  58000.0
6     kumar   27   Benguloor  49000.0
7     shree   29  Maharastra  53000.0
8  chandana   31       Vizag  59375.0
9     Julie   26         Hyd  56000.0
